In [72]:
import numpy as np 
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score


In [112]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
wine = load_wine()
X, Y = wine.data, wine.target
X = X[0:130,:]
Y = (Y[Y != 2])
Y = Y[:,np.newaxis]
#split data into training and test data.
#train_X, test_X, train_y, test_y = train_test_split(X, Y, train_size=0.9,test_size=0.1)
#train_y
#train_y
#print(Y.shape)



In [113]:

def kernel_function(center, data_point,hidden_layer_size,X):
    d = (X.max(axis=0)-X.min(axis=0)).max()  
    sigma = d/np.sqrt(2*hidden_layer_size)
    return np.exp(-(np.linalg.norm(center-data_point)**2)/(2*sigma**2))

def calculate_interpolation_matrix(X,centers,hidden_layer_size):
        G = np.zeros((len(X), hidden_layer_size))
        for data_point_arg, data_point in enumerate(X):
            for center_arg, center in enumerate(centers):
                G[data_point_arg, center_arg] = kernel_function(center, data_point,hidden_layer_size,X)
        print(G)
        return G
    

def rbf_fit(X, Y,hidden_layer_size,weights):
        centers = select_centers(X,hidden_layer_size)
        G = calculate_interpolation_matrix(X,centers,hidden_layer_size)
        weights = np.dot(np.linalg.pinv(G), Y)
        #G = calculate_interpolation_matrix(X,centers)
        predictions = np.dot(G,weights)
        weights = np.dot(np.linalg.pinv(G),Y)
        print(weights)
        predictions = np.dot(G,weights)
        return predictions


def select_centers(X,hidden_layer_size):
    #random_args = np.random.choice(len(X),hidden_layer_size)
    centers = X
    return centers


In [114]:
hidden_layer_size = 130
input_layer_size  = 1
#weights = np.ones((hidden_layer_size,input_layer_size))
#weights = [1,-1,-1,1]   
w=KMeans(n_clusters=hidden_layer_size).fit(X)
weights= np.transpose(w.cluster_centers_)  
print(weights)


[[1.176e+01 1.305e+01 1.200e+01 ... 1.386e+01 1.475e+01 1.225e+01]
 [2.680e+00 1.730e+00 1.510e+00 ... 1.350e+00 1.730e+00 1.730e+00]
 [2.920e+00 2.040e+00 2.420e+00 ... 2.270e+00 2.390e+00 2.120e+00]
 ...
 [1.230e+00 1.120e+00 1.050e+00 ... 1.010e+00 1.250e+00 1.000e+00]
 [2.500e+00 2.910e+00 2.650e+00 ... 3.550e+00 2.730e+00 3.170e+00]
 [6.070e+02 1.150e+03 4.500e+02 ... 1.045e+03 1.150e+03 5.100e+02]]


In [115]:
#predictions = rbf_fit(train_X,train_y,hidden_layer_size,weights)
predictions = rbf_fit(X,Y,hidden_layer_size,weights)

print(predictions)


[[1.00000000e+00 9.37396052e-01 3.68671972e-01 ... 4.50467977e-11
  8.69179192e-16 1.50743449e-07]
 [9.37396052e-01 1.00000000e+00 2.98385085e-01 ... 1.56024713e-10
  3.91486599e-15 4.36363708e-07]
 [3.68671972e-01 2.98385085e-01 1.00000000e+00 ... 1.39885146e-15
  3.81619482e-21 2.97200809e-11]
 ...
 [4.50467977e-11 1.56024713e-10 1.39885146e-15 ... 1.00000000e+00
  3.60895894e-01 4.18027149e-01]
 [8.69179192e-16 3.91486599e-15 3.81619482e-21 ... 3.60895894e-01
  1.00000000e+00 2.34828209e-02]
 [1.50743449e-07 4.36363708e-07 2.97200809e-11 ... 4.18027149e-01
  2.34828209e-02 1.00000000e+00]]
[[ 2.50851054e+02]
 [ 1.32350896e+03]
 [ 1.24406697e+02]
 [-1.22471708e+01]
 [-5.22929267e+01]
 [ 1.49388144e+01]
 [-1.45678878e+01]
 [-1.49872422e+01]
 [-4.00171178e+02]
 [-2.27339065e+03]
 [-1.00568566e+01]
 [ 1.45511679e+02]
 [-2.14090837e+01]
 [ 1.25345645e+01]
 [-1.80039866e-01]
 [ 3.72503974e+01]
 [-4.95375228e+01]
 [ 9.73256286e+01]
 [-1.06093521e-01]
 [ 7.79668229e+02]
 [-6.48822291e+02]
 

In [116]:
for i,_ in enumerate(predictions):
        #print(i)
        if(predictions[i] > 0):
            predictions[i] = 1
        else:
            predictions[i] = 0
print(predictions)
#predictions = predictions[:,np.newaxis]

[[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [118]:
#np.vectorize(train_y)
accuracy_score(Y,predictions)

0.8