In [125]:
import numpy as np 
from sklearn.cluster import KMeans

In [126]:
X_train = np.array([[0,0],[0,1],[1,0],[1,1]])
X_train.shape
Y_train = np.array([[0],[1],[1],[0]])
Y_train.shape

(4, 1)

In [127]:

def kernel_function(center, data_point,hidden_layer_size,X):
    d = (X.max(axis=0)-X.min(axis=0)).max()  
    sigma = d/np.sqrt(2*hidden_layer_size)
    return np.exp(-(np.linalg.norm(center-data_point)**2)/(2*sigma**2))

def calculate_interpolation_matrix(X,centers,hidden_layer_size):
        G = np.zeros((len(X), hidden_layer_size))
        for data_point_arg, data_point in enumerate(X):
            for center_arg, center in enumerate(centers):
                G[data_point_arg, center_arg] = kernel_function(center, data_point,hidden_layer_size,X)
        print(G)
        return G
    

def rbf_fit(X, Y,hidden_layer_size,weights):
        centers = select_centers(X,hidden_layer_size)
        G = calculate_interpolation_matrix(X,centers,hidden_layer_size)
        weights = np.dot(np.linalg.pinv(G), Y)
        #G = calculate_interpolation_matrix(X,centers)
        predictions = np.dot(G,weights)
        weights = np.dot(np.linalg.pinv(G),Y)
        print(weights)
        predictions = np.dot(G,weights)
        return predictions


def select_centers(X,hidden_layer_size):
    #random_args = np.random.choice(len(X),hidden_layer_size)
    centers = X
    return centers


In [128]:
hidden_layer_size = 4
input_layer_size  = 1
#weights = np.ones((hidden_layer_size,input_layer_size))
#weights = [1,-1,-1,1]   
w=KMeans(n_clusters=hidden_layer_size).fit(X_train)
weights= np.transpose(w.cluster_centers_)  
print(weights)


[[0. 0. 1. 1.]
 [1. 0. 1. 0.]]


In [129]:
predictions = rbf_fit(X_train,Y_train,hidden_layer_size,weights)
print(predictions)


[[1.00000000e+00 1.83156389e-02 1.83156389e-02 3.35462628e-04]
 [1.83156389e-02 1.00000000e+00 3.35462628e-04 1.83156389e-02]
 [1.83156389e-02 3.35462628e-04 1.00000000e+00 1.83156389e-02]
 [3.35462628e-04 1.83156389e-02 1.83156389e-02 1.00000000e+00]]
[[-0.03665587]
 [ 1.00100695]
 [ 1.00100695]
 [-0.03665587]]
[[-1.42247325e-16]
 [ 1.00000000e+00]
 [ 1.00000000e+00]
 [-1.42247325e-16]]


In [130]:
for i,_ in enumerate(predictions):
        #print(i)
        if(predictions[i] > 0):
            predictions[i] = 1
        else:
            predictions[i] = 0
print(predictions)

[[0.]
 [1.]
 [1.]
 [0.]]
